version: 2

sources:
  - name: fresh
    description: ""
    database: analytics
    schema: fresh
    tables:
      - name: diary
        description: ""
        columns:
          - name: c1
            data_type: date
            description: ""
          - name: c2
            data_type: varchar
            description: ""
          - name: c3
            data_type: varchar
            description: ""
          - name: c4
            data_type: varchar
            description: ""
          - name: c5
            data_type: varchar
            description: ""
          - name: c6
            data_type: varchar
            description: ""
          - name: c7
            data_type: varchar
            description: ""
          - name: c8
            data_type: date
            description: ""
          - name: c9
            data_type: date
            description: ""

      - name: reviews
        description: ""
        columns:
          - name: date
            data_type: date
            description: ""
          - name: name
            data_type: varchar
            description: ""
          - name: year
            data_type: number
            description: ""
          - name: letterboxduri
            data_type: varchar
            description: ""
          - name: rating
            data_type: number
            description: ""
          - name: rewatch
            data_type: boolean
            description: ""
          - name: review
            data_type: varchar
            description: ""
          - name: tags
            data_type: varchar
            description: ""
          - name: watcheddate
            data_type: date
            description: ""
